### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by lurch**
Fixed Chose -> Choose

### CODE REVIEW

**Comment by spl237** [comment]
Merged - many thanks!

**Comment by lurch** [comment]
Should I also submit an identical PR to https://github.com/RPi-Distro/raspi-config ?

**Comment by spl237** [comment]
Shouldn't be necessary - we merge the version from my repo with that in RPI-Distro, so the changes should appear there anyway.

**Comment by lurch** [comment]
Just out of curiosity, why *is* there a separate copy of `raspi-config` inside this repo?

**Comment by spl237** [comment]
For historical reasons that are too tedious to go into... ;)

**Pull request merged**
