### PR TITLE
Update zh_TW translation.

### PR DESCRIPTION
**Pull request by s8321414**
I update zh_TW translation again, please review and merge it, thanks~

### CODE REVIEW

**Comment by spl237** [comment]
Merged - many thanks!

**Comment by ppigmans** [comment]
if i may ask, what language is zh_TW?

**Comment by s8321414** [comment]
@ppigmans Taiwanese Mandarin (aka Traditional Chinese)

**Comment by ppigmans** [comment]
@s8321414 Oh cool, didnt know that :)

**Comment by s8321414** [comment]
@ppigmans haha, don't worry!

**Pull request merged**
