### PR TITLE
Gtk3

### PR DESCRIPTION
**Pull request by ZanderBrown**
rc_gui ported to Gtk3 as a side project to my pi-conf which i hope might oneday replace it. No real changes other than padding and compileing against gtk3.10 +

### CODE REVIEW

**Comment by ZanderBrown** [comment]
Any thoughts?

**Comment by s8321414** [comment]
:+1:

**Comment by spl237** [comment]
At the moment, pretty much all of the applications that ship by default with the Raspbian image are based on GTK+2.0, which means they have a consistent look and feel. While I have recently modified the PiX GTK+2.0 theme to make it more closely match the default GTK+3.0 theme, there are still several areas where it is significantly different - notably on tabbed interfaces, like that in rc_gui. (As a matter of personal preference, I prefer the GTK+2 tab style to the GTK+3 style, which doesn't actually look like tabs...)

For that reason, I would prefer to maintain visual consistency across our applications, which means sticking with GTK+2.0 as the toolkit for the time being. So thank you for your work on this, but I won't be pulling it into the main codebranch. At some point in the future, we may move everything to GTK+3.0, but it's not planned - and LXQT might have become the default environment by then anyway...

**Comment by ZanderBrown** [comment]
if anyone interested i have been slowly working through the default applications reworking them for Gtk3. lxpolkit works quiet well and i think pi-power is much nicer than lxde-pi-shutdown-helper. currenlty working on lxterminal (renamed pi-term) and libfm before returning to the mess of depreciated code that is LXPanel

**Comment by spl237** [comment]
FYI, the next release of Raspbian will include pishutdown, a replacement for lxde-pi-shutdown-helper, which is ready to go; it'll appear in apt some time in the next month or so.

The version of libfm we use already has a number of Pi-specific patches on top of the default release, and lxpanel has been extensively modified, mostly in the way several plugins work, but there are also changes and bugfixes in the core code. When stretch becomes the stable release, we will move across to the version of lxpanel included in that (currently 0.8.2, but that will probably change before then...) at which point I will merge most of the changes to the current version into that version to create a new custom version for Pi.

Not to discourage you, but we won't be moving Raspbian to GTK+3.0 until a majority of the LXDE standard applications are supporting it upstream. I am very unlikely to merge any GTK+3.0-based changes until that time, and as above, we may decide to move to LXQT instead in the future.

If you are working on parts of LXDE, I'd recommend upstreaming them to the LXDE repos rather than to the Pi-specific repos.

**Comment by ZanderBrown** [comment]
Ok then will do..

**Comment by ZanderBrown** [comment]
Is there somewhere I could see the pishutdown code? it doesn't seem to be in the raspberry pi repo

**Comment by spl237** [comment]
It's in a private repo at the moment; I'll make it public when it goes live on apt.

**Comment by ZanderBrown** [comment]
Ok that'l explain why i couldn't find it :-)

**Comment by lurch** [comment]
See also: https://github.com/RPi-Distro/repo/issues/25

**Pull request closed without merging**
